version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  favoritecite:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
#      перезагрузка при каких либо изменениях
      - ./:/usr/src/app
    depends_on:
#      поднимать сервис только тогда когда запущен postgresdb
      - postgresdb
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - favoritecite
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./staticfiles/:/staticfiles
